# Generated by Django 3.1.7 on 2021-03-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('other_title', models.CharField(blank=True, max_length=255, null=True)),
                ('contributor_names', models.TextField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('recording_label', models.CharField(blank=True, max_length=255, null=True)),
                ('recording_date', models.CharField(blank=True, max_length=255, null=True)),
                ('recording_location', models.CharField(blank=True, max_length=255, null=True)),
                ('recording_repository', models.CharField(blank=True, max_length=255, null=True)),
                ('rights_advisory', models.CharField(blank=True, max_length=255, null=True)),
                ('streaming_url', models.URLField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='songs/')),
            ],
        ),
    ]
