# Generated by Django 3.1.7 on 2021-03-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='description_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
