# Generated by Django 3.1.7 on 2021-03-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0003_auto_20210308_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
