# Generated by Django 3.1.7 on 2021-04-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0004_auto_20210309_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_unique',
            field=models.BooleanField(default=True, help_text='True is no others have same title'),
        ),
        migrations.AddField(
            model_name='song',
            name='public_domain',
            field=models.BooleanField(default=True, help_text='T if recorded prior to 1923'),
        ),
    ]
