# Generated by Django 3.1.7 on 2021-04-25 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0006_song_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongSkip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skipped_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_library.song')),
            ],
        ),
    ]
